-- Multi-entity analytics grain
-- Adds entity_type to daily_* tables and creates daily_metric_dims.
-- Run in the Supabase SQL editor (service role / postgres).
-- Existing rows default to entity_type = 'post'.

-- 1) daily_case_metrics
ALTER TABLE public.daily_case_metrics
  ADD COLUMN IF NOT EXISTS entity_type text NOT NULL DEFAULT 'post';

ALTER TABLE public.daily_case_metrics
  DROP CONSTRAINT IF EXISTS daily_case_metrics_entity_type_check;

ALTER TABLE public.daily_case_metrics
  ADD CONSTRAINT daily_case_metrics_entity_type_check
  CHECK (entity_type IN ('post', 'ad', 'domain'));

ALTER TABLE public.daily_case_metrics
  DROP CONSTRAINT IF EXISTS daily_case_metrics_day_platform_project_unique;

ALTER TABLE public.daily_case_metrics
  DROP CONSTRAINT IF EXISTS daily_case_metrics_day_platform_project_entity_unique;

ALTER TABLE public.daily_case_metrics
  ADD CONSTRAINT daily_case_metrics_day_platform_project_entity_unique
  UNIQUE (date, platform, project_name, entity_type);

CREATE INDEX IF NOT EXISTS daily_case_metrics_project_date_entity_idx
  ON public.daily_case_metrics (project_name, date, entity_type);

-- 2) daily_reviewed_metrics
ALTER TABLE public.daily_reviewed_metrics
  ADD COLUMN IF NOT EXISTS entity_type text NOT NULL DEFAULT 'post';

ALTER TABLE public.daily_reviewed_metrics
  DROP CONSTRAINT IF EXISTS daily_reviewed_metrics_entity_type_check;

ALTER TABLE public.daily_reviewed_metrics
  ADD CONSTRAINT daily_reviewed_metrics_entity_type_check
  CHECK (entity_type IN ('post', 'ad', 'domain'));

ALTER TABLE public.daily_reviewed_metrics
  DROP CONSTRAINT IF EXISTS daily_reviewed_metrics_day_platform_project_unique;

ALTER TABLE public.daily_reviewed_metrics
  DROP CONSTRAINT IF EXISTS daily_reviewed_metrics_day_platform_project_entity_unique;

ALTER TABLE public.daily_reviewed_metrics
  ADD CONSTRAINT daily_reviewed_metrics_day_platform_project_entity_unique
  UNIQUE (date, platform, project_name, entity_type);

CREATE INDEX IF NOT EXISTS daily_reviewed_metrics_project_date_entity_idx
  ON public.daily_reviewed_metrics (project_name, date, entity_type);

-- 3) daily_metric_dims
CREATE TABLE IF NOT EXISTS public.daily_metric_dims (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  date date NOT NULL,
  project_name text NOT NULL,
  entity_type text NOT NULL,
  dim text NOT NULL,
  value text NOT NULL,
  count integer NOT NULL DEFAULT 0,
  CONSTRAINT daily_metric_dims_entity_type_check
    CHECK (entity_type IN ('post', 'ad', 'domain')),
  CONSTRAINT daily_metric_dims_count_nonnegative
    CHECK (count >= 0),
  CONSTRAINT daily_metric_dims_day_project_entity_dim_value_unique
    UNIQUE (date, project_name, entity_type, dim, value),
  CONSTRAINT daily_metric_dims_project_name_fkey
    FOREIGN KEY (project_name) REFERENCES public.project (project_name)
);

CREATE INDEX IF NOT EXISTS daily_metric_dims_project_date_entity_dim_idx
  ON public.daily_metric_dims (project_name, date, entity_type, dim);

ALTER TABLE public.daily_metric_dims ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "authenticated can read daily_metric_dims" ON public.daily_metric_dims;
DROP POLICY IF EXISTS "authenticated can write daily_metric_dims" ON public.daily_metric_dims;
CREATE POLICY "authenticated can write daily_metric_dims"
  ON public.daily_metric_dims
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.daily_metric_dims TO authenticated;
GRANT ALL ON public.daily_metric_dims TO service_role;
DO $$
BEGIN
  GRANT USAGE, SELECT ON SEQUENCE public.daily_metric_dims_id_seq TO authenticated, service_role;
EXCEPTION
  WHEN undefined_table THEN NULL;
END $$;
